spring:
  config:
    name: project2
  datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      password: 
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop  #чтобы при каждом перезапуске не очищалась бд меняется на update

    database: h2
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  port: 8080




